### PR TITLE
fix(sidecar): don't send empty delegations and warn about it

### LINKED ISSUE #587: Warn/Error when sidecar is sending empty delegation list
Consider this logic in the sidecar, run when the beacon node is sending `register_validators` requests.

https://github.com/chainbound/bolt/blob/eed9cec9b644632550479f05823b4487d3ed1ed6/bolt-sidecar/src/client/constraints.rs#L111-L148

If `filtered_delegations` is empty, this is probably a misconfiguration on the user side and we should either panic or print an error/warn message.
Such scenario happens when a user is enabling delegations done with a set of validator public keys that doesn't completely match the set of validator keys used to run the beacon client.

It might be intended behaviour if for example the user wants to run the sidecar but wants to issue commitments only with a subset of its public keys, and just proxy request to regular PBS otherwise.

### PR DESCRIPTION
**Pull request by thedevbirb**
Closes #587

### CODE REVIEW

File: bolt-sidecar/src/client/constraints.rs [hunk 1]
```diff
@@ -140,6 +140,24 @@ impl BuilderApi for ConstraintsClient {
             .cloned()
             .collect::<Vec<_>>();
 
+        if filtered_delegations.is_empty() {
+            warn!("No delegations found for the incoming validator registrations");
+            // Works also with directives like `RUST_LOG=bolt_sidecar=trace`
+            if span_enabled!(Level::TRACE) {
```
Comment (merklefruit) [inline bolt-sidecar/src/client/constraints.rs:146]: nice trick

**Review by merklefruit — APPROVED** [review]

File: bolt-sidecar/src/client/constraints.rs (hunk 1 above)
Comment (mempirate) [reply bolt-sidecar/src/client/constraints.rs:146]: Very nice trick
