### PR TITLE
fix: commitment deadline in case of missed block

### LINKED ISSUE #180: Bug: missed block fails to kick off sidecar round
## Context
To initiate a sidecar "round" i.e. submit constraints, we rely on a new block stream. However, when no block is proposed (missed), we fail to initiate the round. We should look at a more fault-tolerant way of "keeping time", perhaps subscribe to the beacon block stream instead.

## Game plan
- Is there any events stream on the [beacon-API](https://ethereum.github.io/beacon-APIs/#/Events/eventstream) that ticks no matter what? (`head` or `block`)
- If not we should rely on the system clock. The most important thing is that the logic related to timing actually fires.
- Note that we cannot use this system clock to advance the execution / consensus state, because in most cases the block for that slot will not have arrived yet. This needs to be decoupled somehow.

### PR DESCRIPTION
**Pull request by namn-grg**
Fixes #180 

## Summary by CodeRabbit

- **New Features**
	- Enhanced consensus management with the addition of a `consensus_clock` for improved time representation related to consensus slots.
	- New method to retrieve the cached beacon genesis timestamp from the `HeadTracker`.

- **Bug Fixes**
	- Improved resilience in fetching the beacon genesis timestamp with a retry mechanism.

- **Refactor**
	- Simplified `ConsensusState` by removing the `header` field and renaming `update_head` to `update_slot` for clearer slot management.
	- Standardized retry logic for subscribing to new head events in the `HeadTracker`.

- **Tests**
	- Added test cases to verify the correct behavior of the updated slot management functionality.

### CODE REVIEW

File: bolt-sidecar/src/driver.rs [hunk 1]
```diff
@@ -74,17 +96,24 @@ impl<C: StateFetcher, BLS: SignerBLS, ECDSA: SignerECDSA> SidecarDriver<C, BLS,
...
+        // but using beacon node events is easier to work on a custom devnet for now
+        // (as we don't need to specify genesis time and slot duration)
+        let head_tracker = HeadTracker::start(beacon_client.clone());
+
+        // Initialize the consensus clock.
+        let consensus_clock = from_system_time(
+            head_tracker.beacon_genesis_timestamp(),
+            cfg.chain.slot_time(),
+            SLOTS_PER_EPOCH,
+        );
```
Comment (merklefruit) [inline bolt-sidecar/src/driver.rs]: reminder: this is not great because head tracker initializes the genesis timestamp to 0.
We should add a fn to simply async fetch that value instead for safety

This can be done in another issue

File: bolt-sidecar/src/driver.rs [hunk 2]
```diff
@@ -110,6 +139,7 @@ impl<C: StateFetcher, BLS: SignerBLS, ECDSA: SignerECDSA> SidecarDriver<C, BLS,
             mevboost_client,
             api_events_rx,
             payload_requests_rx,
+            consensus_clock,
```
Comment (mempirate) [inline bolt-sidecar/src/driver.rs]: We can already turn it into a stream here!

File: bolt-sidecar/src/state/consensus.rs [hunk 3]
```diff
@@ -117,22 +114,17 @@ impl ConsensusState {
     }
 
     /// Update the latest head and fetch the relevant data from the beacon chain.
-    pub async fn update_head(&mut self, head: u64) -> Result<(), ConsensusError> {
+    pub async fn update_slot(&mut self, head: u64) -> Result<(), ConsensusError> {
```
Comment (mempirate) [inline bolt-sidecar/src/state/consensus.rs]: Rename param `head` -> `slot` for consistency

File: bolt-sidecar/src/driver.rs [hunk 4]
```diff
@@ -35,6 +40,23 @@ pub struct SidecarDriver<C, BLS, ECDSA> {
     mevboost_client: MevBoostClient,
     api_events_rx: mpsc::Receiver<CommitmentEvent>,
     payload_requests_rx: mpsc::Receiver<FetchPayloadRequest>,
+    consensus_clock: Clock<SystemTimeProvider>,
```
Comment (merklefruit) [inline bolt-sidecar/src/driver.rs]: if we only need the SlotStream from the clock, I would prefer to keep that in the struct instead of the Clock.
It should be of type `SlotStream<something>` but if it's an issue let me know!

File: bolt-sidecar/src/driver.rs [hunk 5]
```diff
@@ -74,17 +96,24 @@ impl<C: StateFetcher, BLS: SignerBLS, ECDSA: SignerECDSA> SidecarDriver<C, BLS,
         let (api_events_tx, api_events_rx) = mpsc::channel(1024);
         CommitmentsApiServer::new(api_addr).run(api_events_tx).await;
 
+        // TODO: this can be replaced with ethereum_consensus::clock::from_system_time()
+        // but using beacon node events is easier to work on a custom devnet for now
+        // (as we don't need to specify genesis time and slot duration)
+        let head_tracker = HeadTracker::start(beacon_client.clone());
+
+        // Initialize the consensus clock.
+        let consensus_clock = from_system_time(
```
Comment (merklefruit) [inline bolt-sidecar/src/driver.rs]: can we leave the package name for clarity here? e.g. `clock::from_system_time()` otherwise it's a bit unclear imo

**Review by mempirate — CHANGES_REQUESTED** [review]
Nice one, some smol nits

File: bolt-sidecar/src/driver.rs [hunk 6]
```diff
@@ -132,6 +164,11 @@ impl<C: StateFetcher, BLS: SignerBLS, ECDSA: SignerECDSA> SidecarDriver<C, BLS,
                 Some(payload_request) = self.payload_requests_rx.recv() => {
                     self.handle_fetch_payload_request(payload_request);
                 }
+                Some(slot) = slot_stream.next() => {
+                    if let Err(e) = self.consensus.update_slot(slot).await {
+                        error!(err = ?e, "Failed to update consensus state slot");
+                    }
```
Comment (merklefruit) [inline bolt-sidecar/src/driver.rs]: Awesome!

**Review by merklefruit — CHANGES_REQUESTED** [review]
Very nice work! Just left some minor comments

**Comment by namn-grg** [comment]
@coderabbitai review

**Comment by namn-grg** [comment]
Thanks for the speedy review! Addressed it

File: bolt-sidecar/src/driver.rs (hunk 1 above)
Comment (namn-grg) [reply bolt-sidecar/src/driver.rs]: I added a comment for this.

but I don't understand how the soln for this should be.

```
let genesis_time = loop {
                    match beacon_client.get_genesis_details().await {
                        Ok(genesis_info) => break genesis_info.genesis_time,
                        Err(err) => {
                            warn!(?err, "failed to get genesis details");
                            sleep(RETRY_DELAY).await;
                            continue;
                        }
                    }
};
```

I am fetching the value like this

Comment (merklefruit) [reply bolt-sidecar/src/driver.rs]: on second thought, we should really have this value in `ChainConfig` anyway - for now it's fine though 👍

**Review by merklefruit — APPROVED** [review]
LGTM!
