### PR TITLE
fix: update types & drop bundle support

### LINKED ISSUE #217: Drop support for bundle preconfs
## Context
Bundle preconfs have various negative externalities. Until we figure those out, remove support.

EDIT: we could also loosen bundle specifications by saying they must be executed with an ascending index, but not continuous.

### PR DESCRIPTION
**Pull request by mempirate**
Closes #217

### CODE REVIEW

File: bolt-sidecar/src/driver.rs [hunk 1]
```diff
@@ -220,21 +220,26 @@ impl<C: StateFetcher, BLS: SignerBLS, ECDSA: SignerECDSA> SidecarDriver<C, BLS,
...
+                Ok(signature) => SignedConstraints { message, signature },
+                Err(err) => {
+                    error!(?err, "Failed to sign constraints");
+                    let _ = response.send(Err(CommitmentError::Internal));
+                    return;
+                }
+            };
+
+            ApiMetrics::increment_transactions_preconfirmed(tx_type);
+            self.execution.add_constraint(slot, signed_constraints);
```
Comment (thedevbirb) [inline bolt-sidecar/src/driver.rs:241]:
```suggestion
            let signed_constraint = match self.constraint_signer.sign(&message.digest()).await {
                Ok(signature) => SignedConstraint { message, signature },
                Err(err) => {
                    error!(?err, "Failed to sign constraint");
                    let _ = response.send(Err(CommitmentError::Internal));
                    return;
                }
            };

            ApiMetrics::increment_transactions_preconfirmed(tx_type);
            self.execution.add_constraint(slot, signed_constraint);
```
For clarity that is `signed_constraintS -> `signed_constraint`, also for the type. Can we drop also the `Vec` from `SignedConstraints`? Or it is used elsewhere.

Comment (thedevbirb) [inline bolt-sidecar/src/driver.rs:241]: Does this work if a transaction appears twice, first time in a commitment request with just one tx and the second time in a commitment with a batch of two transactions?
Because there is a risk otherwise we increment the nonce of balance of the user two times

**Review by thedevbirb — COMMENTED** [review]
Two little q's!

File: bolt-sidecar/src/driver.rs (hunk 1 above)
Comment (mempirate) [reply bolt-sidecar/src/driver.rs:241]: If we change it from a `Vec` that would change the constraints-API. We don't use constraint bundles as of now but we might still use it in the future. We just dropped support for bundles from the commitments-API

**Review by merklefruit — APPROVED** [review]

File: bolt-sidecar/src/driver.rs (hunk 1 above)
Comment (mempirate) [reply bolt-sidecar/src/driver.rs:241]: I created a quick test with a duplicate tx in a batch, which should and does fail with nonce too low. It's not exactly what you described but should cover it.

**Review by thedevbirb — APPROVED** [review]
