### PR TITLE
fix: validate tx chain id

### LINKED ISSUE #124: bug(sidecar): validate `chain_id` when accepting a commitment request
when sending a transaction built with the wrong chain_id, the sidecar throws this error:

```
2024-07-05T14:38:09.150194Z ERROR bolt_sidecar: CRITICAL: Error while building local payload at 
slot deadline for 101886 err=InvalidEngineHint("{\"jsonrpc\":\"2.0\",\"id\":1,\"result\":{\"status\":\"INVALID\",
\"latestValidHash\":\"0x92ffd66bbf1e791b2680f6f2b9f7b84abba3cded05eb419fda9dde6f3085c4cd\",\
"validationError\":\"could not apply tx 0 [0x9f654551aa0d7f63fff3267b9deb39b6d8b74e389db9592b951419753991a534]: 
invalid chain id for signer: have 3151908 want 7014190335\"}}\n")
```

we should add a check in `ExecutionState::try_commit` to validate the chain_id according to the configured `ChainConfig`.

### PR DESCRIPTION
**Pull request by namn-grg**
fixes #124 

## Summary by CodeRabbit

- **New Features**
  - Added asynchronous method to retrieve chain ID (`get_chain_id`).
  - Introduced validation for transaction chain ID in `InclusionRequest`.
  - Added chain ID field to `ExecutionState` with corresponding retrieval method.

- **Improvements**
  - Enhanced error handling with new `ChainIdMismatch` variant in `ValidationError`.

- **Bug Fixes**
  - Improved state management and validation for chain ID in `ExecutionState`.

These updates enhance the reliability and functionality of the system by improving chain ID management and validation processes.

### CODE REVIEW

File: bolt-sidecar/src/state/execution.rs [hunk 1]
```diff
@@ -93,6 +99,7 @@ impl<C: StateFetcher> ExecutionState<C> {
             slot: 0,
             account_states: HashMap::new(),
             block_templates: HashMap::new(),
+            chain_id: client.get_chain_id().await?,
             client,
         })
```
Comment (namn-grg) [inline bolt-sidecar/src/state/execution.rs:104]: Another way to do this can be to pass the chain ID value from config as a parameter while initializing the execution state, which felt to me as a dirty/ un-clean way.

Comment (merklefruit) [reply bolt-sidecar/src/state/execution.rs:104]: Yeah this is cleaner, great job

File: bolt-sidecar/src/state/execution.rs [hunk 2]
```diff
@@ -136,6 +148,11 @@ impl<C: StateFetcher> ExecutionState<C> {
             return Err(ValidationError::BaseFeeTooLow(max_basefee as u128));
         }
 
+        // Validate the chain ID
+        if !req.validate_chain_id(self.chain_id()) {
+            return Err(ValidationError::ChainIdMismatch);
+        }
```
Comment (merklefruit) [inline bolt-sidecar/src/state/execution.rs]: can we move this to the top, before `req.tx.ecover_signer()`?
it's a good idea to perform the less expensive checks before the more expensive ones

Comment (namn-grg) [reply bolt-sidecar/src/state/execution.rs]: ah yes good point!

File: bolt-sidecar/src/state/execution.rs [hunk 3]
```diff
@@ -107,6 +114,11 @@ impl<C: StateFetcher> ExecutionState<C> {
         &self.block_templates
     }
 
+    /// Returns the chain ID of the chain
+    pub fn chain_id(&self) -> u64 {
+        self.chain_id
+    }
```
Comment (merklefruit) [inline bolt-sidecar/src/state/execution.rs]: why is this needed? can't we just use `self.chain_id` in `try_commit` below?

Comment (namn-grg) [reply bolt-sidecar/src/state/execution.rs]: right I just thought to have a getter fn but on another thought, it might not be useful, removed

**Review by thedevbirb — APPROVED** [review]
LGTM

**Review by merklefruit — APPROVED** [review]
LGTM!
