### PR TITLE
fix(bolt-sidecar): retry when EL is unavailable

### LINKED ISSUE #369: qol(sidecar): driver initialization fails if execution client hangs
When starting bolt-sidecar with an EL node that's still syncing or is otherwise unreachable, we panic during driver initialization:

```
2024-11-08T15:32:13.710198Z DEBUG bolt_sidecar::chain_io::manager: fetching 1 proposer statuses for chunk 1 of 1
Error: Failed to initialize the sidecar driver with local signer: error sending request for url (http://localhost:8545/)

Caused by:
   0: error sending request for url (http://localhost:8545/)
   1: client error (Connect)
   2: tcp connect error: Connection refused (os error 111)
   3: Connection refused (os error 111)

Location:
    /app/src/chain_io/manager.rs:116:33
```

It would be cleaner to instead output a clear message explaining that the EL node is unreachable and retrying if possible.
We could reuse the `retry_with_backoff` util that was recently added perhaps.

Just to be clear, this _is an error_ but it should be handled more gracefully.

### PR DESCRIPTION
**Pull request by estensen**
Fix https://github.com/chainbound/bolt/issues/369

### CODE REVIEW

File: bolt-sidecar/src/chain_io/manager.rs [hunk 1]
```diff
@@ -70,15 +73,38 @@ impl BoltManager {
...
+                                let decoded_error = utils::try_parse_contract_error(err)
+                                    .wrap_err("Failed to fetch proposer statuses from EL client")?;
+
+                                bail!(generate_bolt_manager_error(
+                                    decoded_error,
+                                    commitment_signer_pubkey,
+                                ))
+                            }
+                        }
+                    }
```
Comment (thedevbirb) [inline bolt-sidecar/src/chain_io/manager.rs]: Here you should be able to avoid a level of indentation by matching the inner enum directly, like so:
```rs
Err(Error::TransportError(RpcError::Transport(err)) => { /* ... */ }
Err(_) => { /* ... */ }
```

**Review by thedevbirb — APPROVED** [review]

File: bolt-sidecar/src/chain_io/manager.rs [hunk 2]
```diff
@@ -70,15 +73,38 @@ impl BoltManager {
...
 
-            let returndata = match self.0.getProposerStatuses(hashes_chunk).call().await {
-                Ok(returndata) => returndata,
-                Err(error) => {
-                    let decoded_error = utils::try_parse_contract_error(error)
-                        .wrap_err("Failed to fetch proposer statuses from EL client")?;
-
-                    bail!(generate_bolt_manager_error(decoded_error, commitment_signer_pubkey));
+            // Retry the contract call with exponential backoff
+            let returndata = retry_with_backoff(MAX_RETRIES, || async {
```
Comment (estensen) [inline bolt-sidecar/src/chain_io/manager.rs]: Need `retry_with_backoff_if`, now it always retries

**Review by thedevbirb — APPROVED** [review]
