### PR TITLE
Remove stale templates in case of missed slots

### LINKED ISSUE #372: Sidecar: invalid transactionCount in state diff
When sending a preconf from an account with transactionCount = 451, the sidecar thinks it should be 453 and errors out. So there seems to be an invalid saved state.
```
2024-11-09T06:10:01.183805Z  INFO bolt_sidecar::driver: Received new commitment request: Inclusion(InclusionRequest { slot: 2935899, txs: [FullTransaction { tx: Eip1559 { transaction: TxEip1559 { chain_id: 17000, nonce: 451, gas_limit: 21678, max_fee_per_gas: 2000000000, max_priority_fee_per_gas: 2000000000, to: Call(0x20a1305ec6c13ffe8e5289f98ba1a18aa262c15e), value: 100000, access_list: AccessList([]), input: 0xc9875994f009ad09cd2b0ac8f00e80a82506236b890cb73f51bb8c92d944bed9 }, signature: Signature { r: 70911031237924722977517981366533583870093632649825913402254977509322941278313, s: 7186853581052735961461052627979384968415863668461660534733526401174972890153, odd_y_parity: false }, hash: 0x096a618aaeb420701a7a93e72e977eb829ba008cb1da7c4ed96d781ceddc2ca4 }, sender: None }], signature: Some(Signature { inner: ecdsa::Signature<Secp256k1>(975AED460B2AE35BE98EF32D928AF49CD9FA150196825446CE5E03B6DA1C6A97406EB60F2BF2A3B26FB4D672547DF04A6F630D6CA4A5B26226E3D1A651E1AABE), v: NonEip155(false), r: 68459893974159813656281994313687018228473545369516553621663955064243894381207, s: 29143632013317231640446067020042608656705398347090635200196181355146835503806 }), signer: Some(0x20a1305ec6c13ffe8e5289f98ba1a18aa262c15e) })
2024-11-09T06:10:01.184183Z DEBUG bolt_sidecar::state::execution: Validating basefee slot_diff=50 basefee=8 max_basefee=4809
2024-11-09T06:10:01.184205Z DEBUG bolt_sidecar::state::execution: Validating transaction account_state=AccountState { transaction_count: 452, balance: 382172748470316506, has_code: false } nonce_diff=1 balance_diff=86779875478816
2024-11-09T06:10:01.184228Z  WARN bolt_sidecar::driver: Execution: failed to validate request err=NonceTooLow(453, 451)
```

### PR DESCRIPTION
**Pull request by thedevbirb**
Closes #372.

In case of missed slots the beacon client does not emit a new head event and the logic to remove a block template is not triggered. As such stale templates are kept which invalidates the nonce and balance checks upon receiving a commitment.

### CODE REVIEW

File: bolt-sidecar/src/state/execution.rs [hunk 1]
```diff
@@ -543,11 +543,27 @@ impl<C: StateFetcher> ExecutionState<C> {
...
-        self.block_templates.remove(&slot)
+    /// Removes all the block templates which slot is less then or equal `slot`, and returns them.
+    ///
+    /// This should be called when we need to propose a block for the given slot, or when a new
+    /// head comes in which makes an older block templates useless.
+    ///
+    /// NOTE: We remove all previous block templates to ensure that, when a new head is received
+    /// from the beacon client, all stale template are cleared. This prevents outdated templates
+    /// from persisting in cases of missed slots, where such events are not emitted.
+    pub fn remove_block_templates(&mut self, slot: u64) -> Vec<BlockTemplate> {
```
Comment (merklefruit) [inline bolt-sidecar/src/state/execution.rs]: what do you think of calling this `remove_block_templates_until` ?

Comment (thedevbirb) [reply bolt-sidecar/src/state/execution.rs]: Gud one

**Review by merklefruit — APPROVED** [review]
